import React, { useEffect } from "react";
import { AuthProvider } from "./context/authContext";
import ScreenMenu from "./components/Menus/ScreenMenu";
import { PostProvider } from "./context/postContext";
import messaging from "@react-native-firebase/messaging";
import { Alert } from "react-native";
import { Notifications } from "react-native-notifications";

const RootNavigation = () => {
  useEffect(() => {
    requestUserPermission();
  }, []);

  useEffect(() => {
    const unsubscribe = messaging().onMessage(async (remoteMessage) => {
      Alert.alert("A new FCM message arrived!", JSON.stringify(remoteMessage));
      Notifications.postLocalNotification({
        title: "Local notification",
        body: "This notification was generated by the app!",
        extra: "data",
      });
    });

    return unsubscribe;
  }, []);

  const requestUserPermission = async () => {
    const authStatus = await messaging().requestPermission();
    const enabled =
      authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
      authStatus === messaging.AuthorizationStatus.PROVISIONAL;

    if (enabled) {
      console.log("Authorization status:", authStatus);
      await messaging()
        .subscribeToTopic("news")
        .then(() => console.log("Subscribed to topic!"));
      const token = await messaging().getToken();
      console.log("token", token);
    }
  };
  const setupNotificationListeners = () => {
    Notifications.events().registerNotificationReceivedForeground(
      (notification, completion) => {
        console.log("Notification received in foreground:", notification);
        completion({ alert: true, sound: true, badge: false });
      }
    );

    Notifications.events().registerNotificationOpened((notification) => {
      console.log("Notification opened:", notification);
    });
  };
  return (
    <AuthProvider>
      <PostProvider>
        <ScreenMenu />
      </PostProvider>
    </AuthProvider>
  );
};

export default RootNavigation;
